baseURL: https://zimu2001.github.io/zmBlog/
languageCode: en-us
title: WZM's Site
theme: "PaperMod"


  
params:
    disableThemeToggle: true # 关闭明暗色调切换
    
    ShowBreadCrumbs: true

    socialIcons: # optional
        - name: "Facebook"
          url: "https://www.facebook.com/"
        - name: "twitter"
          url: "https://twitter.com/"
    profileMode:
        enabled: true
        title: "图片测试" # optional default will be site title
        subtitle: "buaa software"
        imageUrl: "\resources\_gen\images\profilephoto.jpg" # optional
        #imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"
            - name: Post
              url: "/posts"

