baseURL: https://zimu2001.github.io/zmBlog/
languageCode: en-us
title: My New Hugo Site
theme: "PaperMod"


  
params:
    disableThemeToggle: true
    
    ShowBreadCrumbs: true
    socialIcons: # optional
        - name: "<platform>"
          url: "<link>"
        - name: "<platform 2>"
          url: "<link2>"
    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"

